=== nemi-dev/dfm-data/schema/baseitem.json
{
  "$schema": "http://json-schema.org/schema",
  "type": "object",
  "description": "베이스 아이템",
  "required": ["level", "rarity", "itype", "attrs"],
  "properties": {
    "name": { "type": "string", "description": "아이템 이름" },
    "image" : { "type": "string", "description": "아이템 아이콘 이름" },
    "overlay" : { "type": "string", "description": "아이템 오버레이 아이콘 이름 (환영극단 2막 등)"},
    "level" : { "type" : "number", "description": "아이템 레벨 (아이템 착용가능 레벨)" },
    "rarity":   { "type": "string", "description": "아이템 레어도",
      "enum": ["Common", "Uncommon", "Rare", "Unique", "Epic"]
    },
    "itype": { "$ref": "./itype.json" },
    "material": {
      "type": "string",
      "description": "(방어구일 때만) 재질",
      "enum": ["천", "가죽", "경갑", "중갑", "판금"]
    },
    "who": {
      "type": "array",
      "description": "이 아이템을 쓸 수 있는 직업",
      "items": { 
        "$ref": "./dfclassname.json"
      }
    },
    "attrs": {
      "description": "아이템 효과",
      "$ref": "./base-attrs.json"
    },
    "branch": {
      "description": "특정 조건에만 적용되는 효과 모음",
      "type": "array",
      "items": {
        "$ref": "./conditional.json"
      }
    },
    "gives": {
      "description": "특정 조건을 만족할때 파티원 모두에게 적용되는 효과 모음",
      "type": "array",
      "items": {
        "$ref": "./conditional.json"        
      }
    },
    "exclusive": {
      "type": "array",
      "items": {
        "$ref": "./exclusive-set.json"
      }
    }
  },
  "additionalProperties": false
}

=== nemi-dev/dfm-data/data/item/격투가/재빠른 도마뱀 송곳니.json
{
  "name": "재빠른 도마뱀 송곳니",
  "level": 60,
  "itype": "통파",
  "rarity": "Epic",
  "attrs": {
    "atk_ph": 791,
    "atk_mg": 812,
    "def_ph": 866,
    "def_mg": 866,
    "strn": 50,
    "intl": 75,
    "speed_atk": 5,
    "speed_cast": 9,
    "speed_move": 5,
    "AccuPct": 5,
    "crit_ph_pct": 5,
    "crit_mg_pct": 2,
    "Accu": 234,
  
    "cdmg_inc": 25,
    "dmg_inc": 34,
    "misc": ["회피 확률 +3%"]
  }
}
