=== nemi-dev/dfm-data/schema/item.json
{
  "$schema": "http://json-schema.org/schema",
  "type": "object",
  "description": "잘 정리된 아이템",
  "required": ["name", "level", "rarity", "itype", "attrs"],
  "properties": {
    "name": { "type": "string", "description": "아이템 이름" },
    "image" : { "type": "string", "description": "아이템 아이콘 이름" },
    "overlay" : { "type": "string", "description": "아이템 오버레이 아이콘 이름 (환영극단 2막 등)"},
    "level" : { "type" : "number", "description": "아이템 레벨 (아이템 착용가능 레벨)" },
    "rarity":   { "type": "string", "description": "아이템 레어도",
      "enum": ["Common", "Uncommon", "Rare", "Unique", "Epic"]
    },
    "itype": { "$ref": "./itype.json" },
    "setOf":    {
      "description": "이 아이템으로 활성화시킬 수 있는 세트 [ex) 에픽 환영극단, 개막/종막] ",
      "oneOf": [
        {
          "type": "string",
          "enum": ["all"]
        },
        {
          "type": "array",
          "items": { "type": "string" }
        }
      ]
    },
    "who": {
      "type": "array",
      "description": "이 아이템을 쓸 수 있는 직업",
      "items": { 
        "$ref": "./dfclassname.json"
      }
    },
    "content": {
      "description": "이 아이템을 얻을 수 있는 컨텐츠 (환영극단, 오즈마 등)",
      "type": "string"
    },
    "part": {
      "type": "array",
      "description": "(카드일 때만) 이 카드를 바를 수 있는 장비 부위",
      "items": {
        "type": "string",
        "enum": ["무기", "상의", "하의", "머리어깨", "벨트", "신발", "팔찌", "목걸이", "반지", "보조장비", "칭호"]
      }
    },
    "material": {
      "type": "string",
      "description": "(방어구일 때만) 재질",
      "enum": ["천", "가죽", "경갑", "중갑", "판금"]
    },
    "ArtiColor": {
      "type": "string",
      "description": "(아티팩트일 때만) 아티팩트 색",
      "enum": ["Red", "Green", "Blue"]
    },
    "attrs": {
      "description": "아이템 효과",
      "$ref": "./base-attrs.json"
    },
    "branch": {
      "description": "특정 조건에만 적용되는 효과 모음",
      "type": "array",
      "items": {
        "$ref": "./condom.json#/definitions/ConditionalNode"
      }
    },
    "gives": {
      "description": "특정 조건을 만족할때 파티원 모두에게 적용되는 효과 모음",
      "type": "array",
      "items": {
        "$ref": "./condom.json#/definitions/ConditionalNode"        
      }
    },
    "exclusive": {
      "type": "array",
      "items": {
        "$ref": "./condom.json#/definitions/ExclusiveSet"
      }
    }
  },
  "additionalProperties": false
}

=== nemi-dev/dfm-data/data/item/환2/워리어/환-폭풍의 심장 - 팔찌.json
{
  "name": "환(幻): 폭풍의 심장 - 팔찌",
  "image": "환영극단 팔찌",
  "content": "환영극단 2막",
  "who": [ "윈드시어" ],
  "level": 60, "rarity": "Epic", "itype": "팔찌",
  "setOf": ["환(幻): 폭풍의 심장"],
  "attrs": {
    "def_mg": 3117,
    "strn": 30,
    "vit": 76,
    "sk_val": {
      "비공참 3식": 5
    },
    "el_fire": 5,
    "el_ice": 5,
    "el_lght": 5,
    "el_dark": 5
  }
}
